Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/middleware.py", line 12, in process_request
    return save_request.save()
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table hello_requests has no column named priority
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/middleware.py", line 12, in process_request
    return save_request.save()
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table hello_requests has no column named priority
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 20, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 14, in edit_link
    object._meta.app_label,
AttributeError: 'int' object has no attribute '_meta'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 16, in edit_link
    args=(object.id,))
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 536, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 456, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'contenttypes_contenttype_change' with arguments '(8,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 20, in edit_link
    raise NoReverseMatch('This model has not got edit link')
NoReverseMatch: This model has not got edit link
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 20, in edit_link
    raise NoReverseMatch('This model has not got edit link')
NoReverseMatch: This model has not got edit link
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 21, in edit_link
    raise NoReverseMatch("This model hasn't got edit link")
NoReverseMatch: This model hasn't got edit link
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 22, in edit_link
    except object.ObjectDoesNotExist:
AttributeError: 'int' object has no attribute 'ObjectDoesNotExist'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 22, in edit_link
    except object.ObjectDoesNotExist:
AttributeError: 'int' object has no attribute 'ObjectDoesNotExist'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 22, in edit_link
    except object.ObjectDoesNotExist:
AttributeError: 'int' object has no attribute 'ObjectDoesNotExist'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 23, in edit_link
    raise ObjectDoesNotExist("No such model")
ObjectDoesNotExist: No such model
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 23, in edit_link
    raise ObjectDoesNotExist("No such model")
ObjectDoesNotExist: No such model
Internal Server Error: /
Traceback (most recent call last):
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/views.py", line 23, in main
    return render(request, 'hello/index.html', context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/smith/.virtualenvs/42cc/local/lib/python2.7/site-packages/django/template/base.py", line 1125, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/smith/test/FortyTwoTestTask-1/apps/hello/templatetags/hello_tags.py", line 21, in edit_link
    raise NoReverseMatch("This model hasn't got edit link")
NoReverseMatch: This model hasn't got edit link
